---
deployment:
  tasks:
    - export DEPLOYPATH=/home/grupszle/public_html/
    - /bin/cp -R /home/grupszle/repositories/GrupoAda/css $DEPLOYPATH
    - /bin/cp -R /home/grupszle/repositories/GrupoAda/images $DEPLOYPATH
    - /bin/cp -R /home/grupszle/repositories/GrupoAda/imagesGA $DEPLOYPATH
    - /bin/cp -R /home/grupszle/repositories/GrupoAda/rarBackup $DEPLOYPATH
    - /bin/cp /home/grupszle/repositories/GrupoAda/.cpanel.yml $DEPLOYPATH
    - /bin/cp /home/grupszle/repositories/GrupoAda/README.md $DEPLOYPATH
    - /bin/cp /home/grupszle/repositories/GrupoAda/about.html $DEPLOYPATH
    - /bin/cp /home/grupszle/repositories/GrupoAda/contact.html $DEPLOYPATH
    - /bin/cp /home/grupszle/repositories/GrupoAda/index.html $DEPLOYPATH
    - /bin/cp /home/grupszle/repositories/GrupoAda/services.html $DEPLOYPATH
    - /bin/cp /home/grupszle/repositories/GrupoAda/catalogo.pdf $DEPLOYPATH
